#!/bin/bash

#root level functions requiring password for quick-system-info-gui


readadminfile(){

zcat --force "$FILE"*

}

main()
{

case $1 in
    readadminfile)  ACTION="$1"
                    FILE="$2"
    ;;
    journalctl_command) ACTION="$@"
    ;;
esac

$ACTION
}

main "$@"
