#!/bin/bash

#root level functions requiring password for quick-system-info-gui

unset ALLOWED
declare -A ALLOWED=(
    #action     allowed
    list        true
    )


list(){
find /var/log -type f -size +0c ! -name lastlog -name '*log'
}

main()
{
ACTION="$1"

case "${ALLOWED[$ACTION]}" in
    true) $ACTION
          ;;
       *) echo "[Error]: Unknown action '$ACTION'"
          exit 1
          ;;
esac

}

main "$@"
