#!/bin/bash

#root level functions requiring password for quick-system-info-gui

#disable/enable on both systemd and sysV


readadminfile(){
TEMP=$(mktemp quick-system-info-gui.XXXXXX -d)
cp "$1" $TEMP
cat $TEMP/syslog
rm -R $TEMP
}


main()
{
readadminfile "$1"
}

main "$@"
